customized_list = [
# "Presence",
# "Criticality",
"PDU SESSION RESOURCE SETUP REQUEST",
"PDU SESSION RESOURCE SETUP RESPONSE",
"PDU SESSION RESOURCE RELEASE COMMAND",
"PDU SESSION RESOURCE RELEASE RESPONSE",
"PDU SESSION RESOURCE MODIFY REQUEST",
"PDU SESSION RESOURCE MODIFY RESPONSE",
"PDU SESSION RESOURCE NOTIFY",
"PDU SESSION RESOURCE MODIFY INDICATION",
"PDU SESSION RESOURCE MODIFY CONFIRM",
"INITIAL CONTEXT SETUP REQUEST",
"INITIAL CONTEXT SETUP RESPONSE",
"INITIAL CONTEXT SETUP FAILURE",
"UE CONTEXT RELEASE REQUEST",
"UE CONTEXT RELEASE COMMAND",
"UE CONTEXT RELEASE COMPLETE",
"UE CONTEXT MODIFICATION REQUEST",
"UE CONTEXT MODIFICATION RESPONSE",
"UE CONTEXT MODIFICATION FAILURE",
"RRC INACTIVE TRANSITION REPORT",
"CONNECTION ESTABLISHMENT INDICATION",
"AMF CP RELOCATION INDICATION",
"RAN CP RELOCATION INDICATION",
"RETRIEVE UE INFORMATION",
"UE INFORMATION TRANSFER",
"UE CONTEXT SUSPEND REQUEST",
"UE CONTEXT SUSPEND RESPONSE",
"UE CONTEXT SUSPEND FAILURE",
"UE CONTEXT RESUME REQUEST",
"UE CONTEXT RESUME RESPONSE",
"UE CONTEXT RESUME FAILURE",
"HANDOVER REQUIRED",
"HANDOVER COMMAND",
"HANDOVER PREPARATION FAILURE",
"HANDOVER REQUEST",
"HANDOVER REQUEST ACKNOWLEDGE",
"HANDOVER FAILURE",
"HANDOVER NOTIFY",
"PATH SWITCH REQUEST",
"PATH SWITCH REQUEST ACKNOWLEDGE",
"PATH SWITCH REQUEST FAILURE",
"HANDOVER CANCEL",
"HANDOVER CANCEL ACKNOWLEDGE",
"UPLINK RAN STATUS TRANSFER",
"DOWNLINK RAN STATUS TRANSFER",
"HANDOVER SUCCESS",
"UPLINK RAN EARLY STATUS TRANSFER",
"DOWNLINK RAN EARLY STATUS TRANSFER",
"PAGING",
"MULTICAST GROUP PAGING",
"INITIAL UE MESSAGE",
"DOWNLINK NAS TRANSPORT",
"UPLINK NAS TRANSPORT",
"NAS NON DELIVERY INDICATION",
"REROUTE NAS REQUEST",
"NG SETUP REQUEST",
"NG SETUP RESPONSE",
"NG SETUP FAILURE",
"RAN CONFIGURATION UPDATE",
"RAN CONFIGURATION UPDATE ACKNOWLEDGE",
"RAN CONFIGURATION UPDATE FAILURE",
"AMF CONFIGURATION UPDATE",
"AMF CONFIGURATION UPDATE ACKNOWLEDGE",
"AMF CONFIGURATION UPDATE FAILURE",
"AMF STATUS INDICATION",
"NG RESET",
"NG RESET ACKNOWLEDGE",
"ERROR INDICATION",
"OVERLOAD START",
"OVERLOAD STOP",
"UPLINK RAN CONFIGURATION TRANSFER",
"DOWNLINK RAN CONFIGURATION TRANSFER",
"WRITE-REPLACE WARNING REQUEST",
"WRITE-REPLACE WARNING RESPONSE",
"PWS CANCEL REQUEST",
"PWS CANCEL RESPONSE",
"PWS RESTART INDICATION",
"PWS FAILURE INDICATION",
"DOWNLINK UE ASSOCIATED NRPPA TRANSPORT",
"UPLINK UE ASSOCIATED NRPPA TRANSPORT",
"DOWNLINK NON UE ASSOCIATED NRPPA TRANSPORT",
"UPLINK NON UE ASSOCIATED NRPPA TRANSPORT",
"TRACE START",
"TRACE FAILURE INDICATION",
"DEACTIVATE TRACE",
"CELL TRAFFIC TRACE",
"LOCATION REPORTING CONTROL",
"LOCATION REPORTING FAILURE INDICATION",
"LOCATION REPORT",
"UE TNLA BINDING RELEASE REQUEST",
"UE RADIO CAPABILITY INFO INDICATION",
"UE RADIO CAPABILITY CHECK REQUEST",
"UE RADIO CAPABILITY CHECK RESPONSE",
"UE RADIO CAPABILITY ID MAPPING REQUEST",
"UE RADIO CAPABILITY ID MAPPING RESPONSE",
"SECONDARY RAT DATA USAGE REPORT",
"UPLINK RIM INFORMATION TRANSFER",
"DOWNLINK RIM INFORMATION TRANSFER",
"BROADCAST SESSION SETUP REQUEST",
"BROADCAST SESSION SETUP RESPONSE",
"BROADCAST SESSION SETUP FAILURE",
"BROADCAST SESSION MODIFICATION REQUEST",
"BROADCAST SESSION MODIFICATION RESPONSE",
"BROADCAST SESSION MODIFICATION FAILURE",
"BROADCAST SESSION RELEASE REQUEST",
"BROADCAST SESSION RELEASE RESPONSE",
"BROADCAST SESSION RELEASE REQUIRED",
"DISTRIBUTION SETUP REQUEST",
"DISTRIBUTION SETUP RESPONSE",
"DISTRIBUTION SETUP FAILURE",
"DISTRIBUTION RELEASE REQUEST",
"DISTRIBUTION RELEASE RESPONSE",
"MULTICAST SESSION ACTIVATION REQUEST",
"MULTICAST SESSION ACTIVATION RESPONSE",
"MULTICAST SESSION ACTIVATION FAILURE",
"MULTICAST SESSION DEACTIVATION REQUEST",
"MULTICAST SESSION DEACTIVATION RESPONSE",
"MULTICAST SESSION UPDATE REQUEST",
"MULTICAST SESSION UPDATE RESPONSE",
"MULTICAST SESSION UPDATE FAILURE",
"Message Type",
"Cause",
"Criticality Diagnostics",
"Bit Rate",
"Global RAN Node ID",
"Global gNB ID",
"NR CGI",
"Global ng-eNB ID",
"E-UTRA CGI",
"GBR QoS Flow Information",
"QoS Flow Level QoS Parameters",
"QoS Flow List with Cause",
"Trace Activation",
"Core Network Assistance Information for RRC INACTIVE",
"User Location Information",
"Slice Support List",
"Dynamic 5QI Descriptor",
"Allocation and Retention Priority",
"Source to Target Transparent Container",
"Target to Source Transparent Container",
"Handover Type",
"MICO Mode Indication",
"S-NSSAI",
"Target ID",
"Emergency Fallback Indicator",
"Security Indication",
"Non Dynamic 5QI Descriptor",
"Source NG-RAN Node to Target NG-RAN Node Transparent Container",
"Target NG-RAN Node to Source NG-RAN Node Transparent Container",
"Allowed NSSAI",
"Relative AMF Capacity",
"DL Forwarding",
"DRBs to QoS Flows Mapping List",
"Message Identifier",
"Serial Number",
"Warning Area List",
"Number of Broadcasts Requested",
"Warning Type",
"Data Coding Scheme",
"Warning Message Contents",
"Broadcast Completed Area List",
"Broadcast Cancelled Area List",
"Number of Broadcasts",
"Concurrent Warning Message Indicator",
"Cancel-All Warning Messages Indicator",
"Emergency Area ID",
"Repetition Period",
"PDU Session ID",
"QoS Flow Identifier",
"PDU Session Type",
"DRB ID",
"Masked IMEISV",
"New Security Context Indicator",
"Time to Wait",
"Global N3IWF ID",
"UE Aggregate Maximum Bit Rate",
"Security Result",
"User Plane Security Information",
"Index to RAT/Frequency Selection Priority",
"Data Forwarding Accepted",
"Data Forwarding Not Possible",
"Direct Forwarding Path Availability",
"Location Reporting Request Type",
"Area of Interest",
"UE Presence in Area of Interest List",
"UE Radio Capability for Paging",
"Assistance Data for Paging",
"Assistance Data for Recommended Cells",
"Recommended Cells for Paging",
"Paging Attempt Information",
"NG-RAN CGI",
"UE Radio Capability",
"UE Radio Capability – E-UTRA Format",
"Time Stamp",
"Location Reporting Reference ID",
"Data Forwarding Response DRB List",
"Paging Priority",
"Packet Loss Rate",
"Packet Delay Budget",
"Packet Error Rate",
"Averaging Window",
"Maximum Data Burst Volume",
"Priority Level",
"Mobility Restriction List",
"UE Security Capabilities",
"Security Key",
"Security Context",
"IMS Voice Support Indicator",
"Paging DRX",
"RRC Inactive Transition Report Request",
"RRC State",
"Expected UE Behaviour",
"Expected UE Activity Behaviour",
"UE History Information",
"Last Visited Cell Information",
"Last Visited NG-RAN Cell Information",
"Cell Type",
"Associated QoS Flow List",
"Information on Recommended Cells and RAN Nodes for Paging",
"Recommended RAN Nodes for Paging",
"PDU Session Aggregate Maximum Bit Rate",
"Maximum Integrity Protected Data Rate",
"Overload Response",
"Overload Action",
"Traffic Load Reduction Indication",
"Slice Overload List",
"RAN Status Transfer Transparent Container",
"COUNT Value for PDCP SN Length 12",
"COUNT Value for PDCP SN Length 18",
"RRC Establishment Cause",
"Warning Area Coordinates",
"Network Instance",
"Secondary RAT Usage Information",
"Volume Timed Report List",
"Redirection for Voice EPS Fallback",
"UE Retention Information",
"UL Forwarding",
"CN Assisted RAN Parameters Tuning",
"Common Network Instance",
"Data Forwarding Response E-RAB List",
"gNB Set ID",
"RNC-ID",
"Extended RNC-ID",
"RAT Information",
"Extended RAT Restriction Information",
"SgNB UE X2AP ID",
"SRVCC Operation Possible",
"IAB Authorized",
"TSC Traffic Characteristics",
"TSC Assistance Information",
"Periodicity",
"Burst Arrival Time",
"Redundant QoS Flow Indicator",
"Extended Packet Delay Budget",
"Redundant PDU Session Information",
"NB-IoT Default Paging DRX",
"NB-IoT Paging eDRX Information",
"NB-IoT Paging DRX",
"Enhanced Coverage Restriction",
"Paging Assistance Data for CE Capable UE",
"UE Radio Capability ID",
"WUS Assistance Information",
"UE Differentiation Information",
"NB-IoT UE Priority",
"NR V2X Services Authorized",
"LTE V2X Services Authorized",
"NR UE Sidelink Aggregate Maximum Bit Rate",
"LTE UE Sidelink Aggregate Maximum Bit Rate",
"PC5 QoS Parameters",
"Alternative QoS Parameters Set List",
"Alternative QoS Parameters Set Index",
"Alternative QoS Parameters Set Notify Index",
"E-UTRA Paging eDRX Information",
"CE-mode-B Restricted",
"CE-mode-B Support Indicator",
"LTE-M Indication",
"Suspend Request Indication",
"Suspend Response Indication",
"UE User Plane CIoT Support Indicator",
"Global TNGF ID",
"Global W-AGF ID",
"Global TWIF ID",
"W-AGF User Location Information",
"Global eNB ID",
"UE History Information from UE",
"MDT Configuration",
"MDT PLMN List",
"MDT Configuration-NR",
"MDT Configuration-EUTRA",
"M1 Configuration",
"M4 Configuration",
"M5 Configuration",
"M6 Configuration",
"M7 Configuration",
"MDT Location Information",
"Bluetooth Measurement Configuration",
"WLAN Measurement Configuration",
"Sensor Measurement Configuration",
"Event Trigger Logged MDT Configuration",
"NR Frequency Info",
"Area Scope of Neighbour Cells",
"NPN Paging Assistance Information",
"NPN Mobility Information",
"Cell CAG Information",
"Target to Source Failure Transparent Container",
"Target NG-RAN Node to Source NG-RAN Node Failure Transparent Container",
"DAPS Request Information",
"DAPS Response Information",
"Early Status Transfer Transparent Container",
"Extended Slice Support List",
"UE Capability Info Request",
"Extended RAN Node Name",
"MICO All PLMN",
"Source Node ID",
"E-UTRAN Composite Available Capacity Group",
"E-UTRAN Composite Available Capacity",
"E-UTRAN Cell Capacity Class Value",
"E-UTRAN Capacity Value",
"E-UTRAN Radio Resource Status",
"NR Radio Resource Status",
"MBS Session ID",
"MBS Area Session ID",
"MBS Service Area",
"MBS Service Area information",
"MBS Support Indicator",
"MBS Session Setup Request List",
"MBS Session Setup or Modify Request List",
"MBS Session Setup Response List",
"MBS Session Failed to Setup List",
"MBS Session To Release List",
"Multicast Group Paging Area",
"MBS Session Status",
"MRB ID",
"MRB Progress Information",
"Time Synchronisation Assistance Information",
"Survival Time",
"QMC Deactivation",
"QMC Configuration Information",
"UE Application Layer Measurement Configuration Information",
"Available RAN Visible QoE Metrics",
"NR Paging eDRX Information",
"RedCap Indication",
"Target NSSAI Information",
"Target NSSAI",
"UE Slice Maximum Bit Rate List",
"PEIPS Assistance Information",
"5G ProSe Authorized",
"5G ProSe PC5 QoS Parameters",
"Last Visited PSCell Information",
"MBS QoS Flows To Be Setup List",
"Reporting System",
"TAI NSAG Support List",
"NGAP Protocol IE-Id",
"NGAP Protocol IE Support Information",
"NGAP Protocol IE Presence Information",
"NGAP IE Support Information Response List",
"MDT PLMN Modification List",
"Excess Packet Delay Threshold Configuration",
"QoS Flow per TNL Information List",
"UP Transport Layer Information",
"E-RAB ID",
"Transport Layer Address",
"GTP-TEID",
"CP Transport Layer Information",
"TNL Association List",
"QoS Flow per TNL Information",
"TNL Association Usage",
"TNL Address Weight Factor",
"UP Transport Layer Information Pair List",
"UP Transport Layer Information List",
"QoS Flow List with Data Forwarding",
"URI",
"MBS Session TNL Information 5GC",
"Shared NG-U Multicast TNL Information",
"MBS Session TNL Information NG-RAN",
"AMF UE NGAP ID",
"RAN UE NGAP ID",
"GUAMI",
"NAS-PDU",
"PLMN Identity",
"SON Configuration Transfer",
"SON Information",
"SON Information Reply",
"Xn TNL Configuration Info",
"TAC",
"TAI",
"AMF Set ID",
"Routing ID",
"NRPPa-PDU",
"RAN Paging Priority",
"EPS TAC",
"EPS TAI",
"UE Paging Identity",
"AMF Pointer",
"5G-S-TMSI",
"AMF Name",
"Paging Origin",
"UE Identity Index Value",
"Periodic Registration Update Timer",
"UE-associated Logical NG-connection List",
"NAS Security Parameters from NG-RAN",
"Source to Target AMF Information Reroute",
"RIM Information Transfer",
"RIM Information",
"LAI",
"Extended Connected Time",
"End Indication",
"Inter-system SON Configuration Transfer",
"Inter-system SON Information",
"SON Information Report",
"Inter-system SON Information Report",
"Failure Indication",
"Inter-system Failure Indication",
"HO Report",
"Inter-system HO Report",
"UE RLF Report Container",
"NID",
"CAG ID",
"NPN Support",
"Allowed PNI-NPN List",
"NPN Access Information",
"Cell CAG List",
"UL CP Security Information",
"DL CP Security Information",
"Configured TAC Indication",
"Extended AMF Name",
"Extended UE Identity Index Value",
"NR NTN TAI Information",
"Inter-system SON Information Request",
"Inter-system SON Information Reply",
"Inter-system Cell Activation Request",
"Inter-system Cell State Indication",
"Inter-system Cell Activation Reply",
"Inter-system Resource Status Request",
"Inter-system Resource Status Report",
"Inter-system Resource Status Reply",
"Hashed UE Identity Index Value",
"PDU Session Resource Setup Request Transfer",
"PDU Session Resource Setup Response Transfer",
"PDU Session Resource Modify Request Transfer",
"PDU Session Resource Modify Response Transfer",
"PDU Session Resource Notify Transfer",
"PDU Session Resource Modify Indication Transfer",
"PDU Session Resource Modify Confirm Transfer",
"Path Switch Request Transfer",
"Path Switch Request Acknowledge Transfer",
"Handover Command Transfer",
"Handover Request Acknowledge Transfer",
"PDU Session Resource Release Command Transfer",
"PDU Session Resource Notify Released Transfer",
"Handover Required Transfer",
"Path Switch Request Setup Failed Transfer",
"PDU Session Resource Setup Unsuccessful Transfer",
"PDU Session Resource Modify Unsuccessful Transfer",
"Handover Preparation Unsuccessful Transfer",
"Handover Resource Allocation Unsuccessful Transfer",
"Path Switch Request Unsuccessful Transfer",
"PDU Session Resource Release Response Transfer",
"PDU Session Resource Modify Indication Unsuccessful Transfer",
"Secondary RAT Data Usage Report Transfer",
"UE Context Resume Request Transfer",
"UE Context Resume Response Transfer",
"UE Context Suspend Request Transfer",
"MBS Session Setup or Modification Request Transfer",
"MBS Session Setup or Modification Response Transfer",
"MBS Session Setup or Modification Failure Transfer",
"MBS Distribution Setup Request Transfer",
"MBS Distribution Setup Response Transfer",
"MBS Distribution Setup Unsuccessful Transfer",
"MBS Distribution Release Request Transfer",
"Multicast Session Activation Request Transfer",
"Multicast Session Deactivation Request Transfer",
"Multicast Session Update Request Transfer",
"MBS Session Release Response Transfer"
]