package ie

type AssistanceDataForPaging struct {
AssistanceDataForRecommendedCells	*AssistanceDataForRecommendedCells
PagingAttemptInformation	*PagingAttemptInformation
NpnPagingAssistanceInformation	*NpnPagingAssistanceInformation
PagingAssistanceDataForCeCapableUe	*PagingAssistanceDataForCeCapableUe
}
