package ie

type DownlinkRanConfigurationTransfer struct {
MessageType	*MessageType
SonConfigurationTransfer	*SonConfigurationTransfer
EnDcSonConfigurationTransfer	*[]byte
InterSystemSonConfigurationTransfer	*InterSystemSonConfigurationTransfer
}
