package ie

type EUtranCompositeAvailableCapacityGroup struct {
	CompositeAvailableCapacityDownlink *EUtranCompositeAvailableCapacity
	CompositeAvailableCapacityUplink   *EUtranCompositeAvailableCapacity
}
