package ie

type HandoverRequestAcknowledgeTransfer struct {
DlNgUUpTnlInformation	*UpTransportLayerInformation
DlForwardingUpTnlInformation	*UpTransportLayerInformation
SecurityResult	*SecurityResult
QosFlowSetupResponseList	*QosFlowListWithDataForwarding
QosFlowFailedToSetupList	*QosFlowListWithCause
DataForwardingResponseDrbList	*DataForwardingResponseDrbList
AdditionalDlUpTnlInformationForHoList	*[]AdditionalDlUpTnlInformationForHoItem
UlForwardingUpTnlInformation	*UpTransportLayerInformation
AdditionalUlForwardingUpTnlInformation	*UpTransportLayerInformationList
DataForwardingResponseERabList	*DataForwardingResponseERabList
RedundantDlNgUUpTnlInformation	*UpTransportLayerInformation
UsedRsnInformation	*RedundantPduSessionInformation
GlobalRanNodeIdOfSecondaryNgRanNode	*GlobalRanNodeId
MbsSupportIndicator	*MbsSupportIndicator
}

type AdditionalDlUpTnlInformationForHoItem struct {
AdditionalDlNgUUpTnlInformation	*UpTransportLayerInformation
AdditionalQosFlowSetupResponseList	*QosFlowListWithDataForwarding
AdditionalDlForwardingUpTnlInformation	*UpTransportLayerInformation
AdditionalRedundantDlNgUUpTnlInformation	*UpTransportLayerInformation
}
