package ie

type HandoverRequest struct {
MessageType	*MessageType
AmfUeNgapId	*AmfUeNgapId
HandoverType	*HandoverType
Cause	*Cause
UeAggregateMaximumBitRate	*UeAggregateMaximumBitRate
CoreNetworkAssistanceInformationForRrcInactive	*CoreNetworkAssistanceInformationForRrcInactive
UeSecurityCapabilities	*UeSecurityCapabilities
SecurityContext	*SecurityContext
NewSecurityContextIndicator	*NewSecurityContextIndicator
Nasc	*NasPdu
PduSessionResourceSetupList	*[]PduSessionResourceSetupItem
AllowedNssai	*AllowedNssai
TraceActivation	*TraceActivation
MaskedImeisv	*MaskedImeisv
SourceToTargetTransparentContainer	*SourceToTargetTransparentContainer
MobilityRestrictionList	*MobilityRestrictionList
LocationReportingRequestType	*LocationReportingRequestType
RrcInactiveTransitionReportRequest	*RrcInactiveTransitionReportRequest
Guami	*Guami
RedirectionForVoiceEpsFallback	*RedirectionForVoiceEpsFallback
CnAssistedRanParametersTuning	*CnAssistedRanParametersTuning
SrvccOperationPossible	*SrvccOperationPossible
IabAuthorized	*IabAuthorized
EnhancedCoverageRestriction	*EnhancedCoverageRestriction
UeDifferentiationInformation	*UeDifferentiationInformation
NrV2XServicesAuthorized	*NrV2XServicesAuthorized
LteV2XServicesAuthorized	*LteV2XServicesAuthorized
NrUeSidelinkAggregateMaximumBitRate	*NrUeSidelinkAggregateMaximumBitRate
LteUeSidelinkAggregateMaximumBitRate	*LteUeSidelinkAggregateMaximumBitRate
Pc5QosParameters	*Pc5QosParameters
CeModeBRestricted	*CeModeBRestricted
UeUserPlaneCiotSupportIndicator	*UeUserPlaneCiotSupportIndicator
ManagementBasedMdtPlmnList	*MdtPlmnList
UeRadioCapabilityId	*UeRadioCapabilityId
ExtendedConnectedTime	*ExtendedConnectedTime
TimeSynchronisationAssistanceInformation	*TimeSynchronisationAssistanceInformation
UeSliceMaximumBitRateList	*UeSliceMaximumBitRateList
Ie5GProseAuthorized	*Ie5GProseAuthorized
Ie5GProseUePc5AggregateMaximumBitRate	*NrUeSidelinkAggregateMaximumBitRate
Ie5GProsePc5QosParameters	*Ie5GProsePc5QosParameters
}

type PduSessionResourceSetupItem struct {
PduSessionId	*PduSessionId
SNssai	*SNssai
HandoverRequestTransfer	*[]byte
PduSessionExpectedUeActivityBehaviour	*ExpectedUeActivityBehaviour
}
