package ie

type InterSystemSonInformation struct {
	ChoiceInterSystemSonInformation *ChoiceInterSystemSonInformation
}

type ChoiceInterSystemSonInformation struct {
	InterSystemSonInformationReport  *InterSystemSonInformationReport
	InterSystemSonInformationRequest *InterSystemSonInformationRequest
	InterSystemSonInformationReply   *InterSystemSonInformationReply
}
