package ie

type MulticastSessionUpdateRequestTransfer struct {
MbsSessionId	*MbsSessionId
MbsServiceArea	*MbsServiceArea
MbsQosFlowsToBeSetupOrModifiedList	*MbsQosFlowsToBeSetupList
MbsQosFlowToReleaseList	*QosFlowListWithCause
MbsSessionTnlInformation5Gc	*MbsSessionTnlInformation5Gc
}
