package ie

type NgapIeSupportInformationResponseList struct {
NgapIeSupportInformationResponseItem	*NgapIeSupportInformationResponseItem
}

type NgapIeSupportInformationResponseItem struct {
NgapProtocolIeId	*NgapProtocolIeId
NgapProtocolIeSupportInformation	*NgapProtocolIeSupportInformation
NgapProtocolIePresenceInformation	*NgapProtocolIePresenceInformation
}
