package ie

type QmcConfigurationInformation struct {
	UeApplicationLayerMeasurementInformationList *[]UeApplicationLayerMeasurementInformationItem
}

type UeApplicationLayerMeasurementInformationItem struct {
	UeApplicationLayerMeasurementConfigurationInformation *UeApplicationLayerMeasurementConfigurationInformation
}
