package ie

type SecurityIndication struct {
IntegrityProtectionIndication	*[]byte
ConfidentialityProtectionIndication	*[]byte
MaximumIntegrityProtectedDataRateUplink	*MaximumIntegrityProtectedDataRate
MaximumIntegrityProtectedDataRateDownlink	*MaximumIntegrityProtectedDataRate
}
