package ie

type TargetNgRanNodeToSourceNgRanNodeFailureTransparentContainer struct {
CellCagInformation	*CellCagInformation
NgapIeSupportInformationResponseList	*NgapIeSupportInformationResponseList
}
