ies.append({ "iei" : "Message Type", "level" : "0", "presence" : "M", "type" : ""})
ies.append({ "iei" : "AMF UE NGAP ID", "level" : "0", "presence" : "M", "type" : ""})
ies.append({ "iei" : "RAN UE NGAP ID", "level" : "0", "presence" : "M", "type" : ""})
ies.append({ "iei" : "PDU Session Resource Setup Response List", "level" : "0", "presence" : "", "type" : ""})
ies.append({ "iei" : "PDU Session Resource Setup Response Item", "level" : "1", "presence" : "", "type" : ""})
ies.append({ "iei" : "PDU Session ID", "level" : "2", "presence" : "M", "type" : ""})
ies.append({ "iei" : "PDU Session Resource Setup Response Transfer", "level" : "2", "presence" : "M", "type" : "OCTET STRING"})
ies.append({ "iei" : "PDU Session Resource Failed to Setup List", "level" : "0", "presence" : "", "type" : ""})
ies.append({ "iei" : "PDU Session Resource Failed to Setup Item", "level" : "1", "presence" : "", "type" : ""})
ies.append({ "iei" : "PDU Session ID", "level" : "2", "presence" : "M", "type" : ""})
ies.append({ "iei" : "PDU Session Resource Setup Unsuccessful Transfer", "level" : "2", "presence" : "M", "type" : "OCTET STRING"})
ies.append({ "iei" : "Criticality Diagnostics ", "level" : "0", "presence" : "O", "type" : ""})
ies.append({ "iei" : "User Location Information", "level" : "0", "presence" : "O", "type" : ""})
